parser: babel-eslint
extends:
  - airbnb-base
  - plugin:flowtype/recommended
plugins:
  - flowtype
  - eslint-plugin-import-order-alphabetical
env:
  node: true
  mocha: true
rules:
  no-param-reassign: "off"
  no-console: "off"
  import/order: [error, newlines-between: always]
  import-order-alphabetical/order: [error]
  import/no-unresolved:
    - error
    - commonjs: true
      ignore:
        - ^aws-sdk$
        - ^oracledb$
        - ^request-promise-native$
        - ^./contrib/contrib$
settings:
  import/resolver:
    alias:
      - ['errors', './errors']
      - ['middlewares', './middlewares']
      - ['utils', './utils']
      - ['paths', './api/v1/paths']
    babel-module: {}
